
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('notes').del()
    .then(function () {
      // Inserts seed entries
      return knex('notes').insert([
        {id: 1, title: '\'This is What You Came For\' by Calvin Harris ft. Rihanna lyrics', textBody: 'Baby, this is what you came for / Lightning strikes every time she moves / And everybody\'s watching her / But she\'s looking at you, oh, oh / You, oh, oh, you, oh, oh / You, oh, oh, you, oh, oh / You, oh, oh / Oh, oh / Baby, this is what you came for / Lightning strikes every time she moves / And everybody\'s watching her / But she\'s looking at you, oh, oh / You, oh, oh, you, oh, oh / You, oh, oh, you, oh, oh / You, oh, oh / Oh, oh / You, oh, oh, you, oh, oh / You, oh, oh, you, oh, oh / You, oh, oh, you, oh, oh / Oh, oh / We go fast till they can\'t replay / Who knows why it\'s gotta be this way / We say nothing more than we need / I say \"your place\" when we leave / Baby, this is what you came for / Lightning strikes every time she moves / And everybody\'s watching her / But she\'s looking at you, oh, oh / You, oh, oh, you, oh, oh / You, oh, oh, you, oh, oh / You, oh, oh / Oh, oh / You, oh, oh, you, oh, oh / You, oh, oh, you, oh, oh / You, oh, oh, you, oh, oh / Oh, oh / Baby, this is what you came for / Lightning strikes every time she moves / Yeah / Baby, this is what you came for / Lightning strikes every time she moves / And everybody\'s watching her / But she\'s looking at you, oh, oh / You, oh, oh, you, oh, oh / You, oh, oh, you, oh, oh / You, oh, oh / Oh, oh / You, oh, oh, you, oh, oh / You, oh, oh, you, oh, oh / You, oh, oh, you, oh, oh / Oh, oh', tags: 'lyrics'},
        {id: 2, title: '\'Desire\' by Years and Years lyrics', textBody: 'I must be tough / I must behave, I must keep fighting / Don\'t give it up / I want to keep us compromising / Open your arms and pray / To the truth that you\'re denying / Give in to the game / To the sense that you\'ve been hiding / Is it desire / Or is it love that I\'m feeling for you / I want desire \'Cause your love only gets me abused / Only gets me abused / Only gets me abused / Give me that rush / I want to show you what you\'ve been missing / Am I enough / To keep your other lovers hidden / Open your arms and pray / To the truth that you\'re denying / Give in to the game / To the sense that you\'ve been hiding / Is it desire / Or is it love that I\'m feeling for you / I want desire / \'Cause your love only gets me abused / Is it desire / Or is it love that I\'m feeling for you / I want desire / I wanna see what you\'re willing to lose / Only gets me abused / Only gets me abused', tags: 'lyrics'},
        {id: 3, title: '\'Thunderclouds\' by LSD lyrics', textBody: '[Verse 1: Sia] / All I need is one / One old man is enough / Babe, you got it wrong / Just turn your fears into trust, to trust / [Pre-Chorus: Sia & Labrinth] / Where\'d the love go? / When all is said and done? / Hey now put your hands in the air / I\'ma go through your stuff / Where\'d the love go? / You put the running into run / You asking me to stay / But I never met a girl I could trust / [Chorus: Labrinth & Sia, Both] / You\'re sayin\' those words like you hate me now (wo-oah) / Our house is burning when you’re raisin’ Hell (wo-oah) / Here in the ashes, your soul cries out (a-a-ah) / But don’t be afraid of these thunderclouds / These thunderclouds, oh no / These thunderclouds, oh no, no / [Verse 2: Labrinth] / All I need is love (da-dum, dum, dum) / All I need is a word (da-dum, dum, dum) / All I need is us (da-dum, dum, dum) / You turn nouns into verbs, to verbs / [Pre-Chorus: Labrinth & Sia] / Where did love go? / When all is said and done? / Hey now put your hands in the air / I\'ma go through your stuff / Where did love go? / You put the running into run / You asking me to stay / But I never met a man I could trust / [Chorus: Sia & Both] / You\'re sayin\' those words like you hate me now (wo-oah) / Our house is burning when you\'re raisin\' Hell (wo-oah) / Here in the ashes,​ your soul cries out (a-a-ah) / But don’t be afraid of these thunderclouds / These thunderclouds, oh no / These thunderclouds, oh no, no / These thunderclouds, oh no / These thunderclouds, oh no, no / [Outro: Sia] / These thunderclouds / These thunderclouds / These thunderclouds / Ohh', tags: 'lyrics'}
      ]);
    });
};
