module.exports = [
  {
    title: 'Stuff you learned',
    text_body: 'There are so many important things you have learned.',
    created_at: '2018-08-01 5:45:12',
    user_id: 1,
    left: -1,
    right: 2,
  },
  {
    title: 'You never forget anything',
    text_body: "There's a time and a place.",
    created_at: '2018-08-02 7:45:12',
    user_id: 1,
    left: 1,
    right: 3,
  },
  {
    title: 'Cigarettes Kill',
    text_body: '98% of smokers are soldiers.',
    created_at: '2018-08-05 5:35:12',
    user_id: 1,
    left: 2,
    right: 4,
  },
  {
    title: "Originally Fifth",
    text_body: '08% of smokers are soldiers.',
    created_at: '2018-08-05 5:35:12',
    user_id: 1,
    left: 3,
    right: 5,
  },
  {
    title: "Originally Sixth",
    text_body: '08% of smokers are soldiers.',
    created_at: '2018-08-05 5:35:12',
    user_id: 1,
    left: 4,
    right: -1,
  },
];
